language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - rbx-2
  - jruby
  
gemfile:
  - Gemfile
  - Gemfile.ActiveSupport
  
env:
  - ''
  - activesupport=3.2.18
  - activesupport=4.1.1
  - activesupport=master
  
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
    - rvm: ruby-head
  exclude:
    - gemfile: Gemfile.ActiveSupport
      env: ''
    - gemfile: Gemfile
      env: activesupport=3.2.18
    - gemfile: Gemfile
      env: activesupport=4.1.1
    - gemfile: Gemfile
      env: activesupport=master
      
branches:
  except:
    - gh-pages
    
after_success:
  - coveralls
  
deploy:
  provider: rubygems
  api_key:
    secure: KjncTxhljBTFpb6jy7aUPqjGXkqk/BNU1J3I//sBet1KZw9ir10EHy+txHKZoXIpH6C7iDS2uORN/6LzoCQL5KWf9pr6mmA40q96CIfLFutOcvuXpLeUmEpzaTqZxj+GZtM50/amI4iHe2JV3k+1outWDJ7+Wf14zBiYQnoAAAI=
  on:
    all_branches: true
