language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - rbx-2
  - jruby
  
gemfiles:
  - Gemfile
  - Gemfile.ActiveSupport

env:
  - "activesupport="
  - "activesupport=3.2.18"
  - "activesupport=4.1.1"
  - "activesupport=master"

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
    - rvm: ruby-head
    
branches:
  except:
    - gh-pages

after_success:
  - coveralls
